### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by mathog** [ekg/ogap#6]
This program was referenced in the example for freebayes.  It would not build with gcc (GCC) 8.3.1 on CentOS 8.2.
Commands were:

```
  pversion=0.0.0
  package=ogap
  cd /usr/common/src
  git clone --recursive https://github.com/ekg/ogap.git
  mv ogap ${package}-${pversion}
  cd ${package}-${pversion}
  make 2>&1 | tee build_2020_10_01.log

```

It failed at:

```
[ 93%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_random.cpp.o
[ 94%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_resolve.cpp.o
/usr/common/src/ogap-0.0.0/bamtools/src/toolkit/bamtools_resolve.cpp: In member function ‘bool BamTools::ResolveTool::ReadNamesFileReader::Read(std::map<std::__cxx11::basic_string<char>, ReadGroupResolver>&)’:
/usr/common/src/ogap-0.0.0/bamtools/src/toolkit/bamtools_resolve.cpp:401:74: error: no matching function for call to ‘make_pair<std::__cxx11::string, bool>(__gnu_cxx::__alloc_traits<std::allocator<std::__cxx11::basic_string<char> >, std::__cxx11::basic_string<char> >::value_type&, bool)’
         resolver.ReadNames.insert( make_pair<string,bool>(fields[1], true) ) ;

```
The build log is attached
[build_2020_10_01.log](https://github.com/ekg/ogap/files/5314325/build_2020_10_01.log)
